#!/bin/sh

# Oopss.org [http://oopss.org]
# Thomas Martin <thomas@oopss.org>

set -e
LC_ALL=C

# customizable settings
LXC_VG_NAME="lxc"
LXC_PATH="/var/lib/lxc"
DEBIAN_PACKAGES="openssh-server,net-tools,netbase,iputils-ping,dnsutils,ifupdown"
DEBIAN_SUITE="squeeze"
NETWORK="10.42.0"
NETMASK="255.255.255.0"
GATEWAY="10.42.0.254"
DNS="10.42.0.254"
TIMEZONE="Europe/Paris"
SSH_PUBFILE="/root/.ssh/id_rsa.pub"

usage() {
	cat <<EOT
Usage: $0 HOSTNAME DISKSIZE NUMBER

Create LXC virtual machine.

Example :
$0 test1.oopss.net 5G 42
EOT
}

if [ $# != 3 ]; then
	usage
	exit 1
fi

set_var() {
	printf "%-20s %s\n" $1 $2
	eval $1=$2
}

echo 
set_var lxc_hostname "$1"
set_var lxc_name $(echo $lxc_hostname | sed 's/\..*//')
set_var lxc_rootpath "$LXC_PATH/$lxc_name"
set_var lxc_rootfs "$lxc_rootpath/rootfs"
set_var lvm_disksize "$2"
set_var lvm_volpath "/dev/mapper/$LXC_VG_NAME-$lxc_name"
set_var ipaddr "$NETWORK.$3"

echo $vars
echo -n "Create ? "
read res
if [ "$res" != 'y' ] && [ "$res" != "Y" ]; then
	echo "Aborting."
	exit 1
fi

echo
echo "creating logical volume $lvm_volpath"
lvcreate -L $lvm_disksize -n $lxc_name $LXC_VG_NAME >/dev/null

echo "creating filesystem on $lvm_volpath"
mkfs.ext4 -q $lvm_volpath

echo "creating root directory $lxc_rootpath"
mkdir $lxc_rootpath

echo "adding entry in /etc/fstab"
echo "$lvm_volpath $lxc_rootpath ext4 defaults 0 2" >>/etc/fstab

echo "mount $lvm_volpath on $lxc_rootpath using fstab"
mount $lxc_rootpath

echo "populating $lxc_rootfs using debootstrap"
debootstrap --verbose --variant=minbase --arch=amd64 --include $DEBIAN_PACKAGES $DEBIAN_SUITE $lxc_rootfs >/dev/null

echo "networking : setting hostname"
echo $lxc_hostname >"$lxc_rootfs/etc/hostname"

echo "networking : setting DNS resolver $net_resolver"
echo "nameserver $DNS" >"$lxc_rootfs/etc/resolv.conf"

echo "networking : setting IP configuration"
cat <<EOT >"$lxc_rootfs/etc/network/interfaces"
auto eth0
iface eth0 inet static
    address $ipaddr
    netmask $NETMASK
    gateway $GATEWAY
EOT

echo "disabling useless tty"
sed -i 's/^[1-6]:/#&/' "$lxc_rootfs/etc/inittab"

echo "remove pointless services in a container"
chroot $lxc_rootfs /usr/sbin/update-rc.d -f umountfs remove >/dev/null
chroot $lxc_rootfs /usr/sbin/update-rc.d -f hwclock.sh remove >/dev/null
chroot $lxc_rootfs /usr/sbin/update-rc.d -f hwclockfirst.sh remove >/dev/null

echo "disabling root password"
chroot $lxc_rootfs passwd -l root >/dev/null

echo "adding SSH keys"
mkdir -p -m 700 "$lxc_rootfs/root/.ssh/"
[ -f $SSH_PUBFILE ] && cp $SSH_PUBFILE "$lxc_rootfs/root/.ssh/authorized_keys"

echo "setting timezone $TIMEZONE"
ln -fs /usr/share/zoneinfo/$TIMEZONE /etc/localtime

echo
echo "Done. Config file : $lxc_rootfs/config"

